services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sopaletras
      POSTGRES_PASSWORD: sopaletras
      POSTGRES_DB: sopa-letras
    ports:
      - "5432:5432"
    networks:
      - sopaletras
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sopaletras -d sopa-letras"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - sopaletras

  backend:
    build:
      context: ../../../../
      dockerfile: Dockerfile
    container_name: sopa-letras
    ports:
      - "9090:9090"
    expose:
      - "9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sopa-letras
      SPRING_DATASOURCE_USERNAME: sopaletras
      SPRING_DATASOURCE_PASSWORD: sopaletras
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sopaletras
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sopaletras:
    driver: bridge