services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sopaletras
      POSTGRES_PASSWORD: sopaletras
      POSTGRES_DB: sopa-letras
    ports:
      - "5432:5432"
    networks:
      - sopaletras

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - sopaletras

networks:
  sopaletras:
    driver: bridge